name: phoenix_wings
description: Phoenix Channel client for Dart
version: 0.3.0
authors:
  - Loic Tosser <loic@kalvad.com>
  - Emilien Roussel <emilien@kalvad.com>
  - Emilmfeckie<mfeckie@gmail.com>
homepage: https://github.com/Opaala/phoenix_wings

dev_dependencies:
  dartdoc: "0.37.0"
  test: "1.15.6"
  mockito: "4.1.1"
  stream_channel: "2.0.0"
  intl: "0.16.1"

environment:
  sdk: '>=2.2.0 <3.0.0'
